walkmod-license-applier-plugin
==============================
Raquel Pau <raquelpau@gmail.com>

image:https://travis-ci.org/rpau/walkmod-license-applier-plugin.svg?branch=master["Build Status", link="https://travis-ci.org/rpau/walkmod-license-applier-plugin"]

This is a walkmod plugin to add license headers in Java source files. By default, it add your license header if it is missing in your source files. 
However, there are the following actions:

* update: updates the existing header with a new one.
* check: checks if the header is missing in some source file but it does not change any source file.
* remove: removes the existing header.
* reformat: adds headers if they are missing (default option).

== Usage
1) Check that your walkmod version is > = 2.2.0.

2) In order to configure this convention to apply or update a license to all your source files, execute the following command:

----
walkmod add -DlicenseFile=src/main/walkmod/license-applier/license.txt -Daction=reformat license-applier
----

And then, to see the results:
----
walkmod apply
----

== Contributing

If you want to hack on this, fork it, improve it and send me a pull request.

To get started using it, just clone it and call mvn install. 


